version: '3.4'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./tmp/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  api:
    build: ./api/
    command: ["./main"]
    depends_on:
      - "redis"
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - DEBUG_ENVIRONMENT=true
  
  app:
    build: ./app-client/
    depends_on:
      - "api"
    ports:
      - "3000:3000"
