name: Project
on: [push]
jobs:

  redis:
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: redis
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v1

  api:
    name: api
    runs-on: ubuntu-latest
    needs: redis
    timeout-minutes: 7
    env:
       GO111MODULE: on
    steps:
      - name: Set up Go 1.13.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        working-directory: ./api
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        working-directory: ./api
        run: go build -o api cmd/main.go
